<script>
    export default {
        name: 'description',
        components: {},
        props: {},
        computed: {
            description() {
                return this.$store.state.ui.description;
            }
        },
        methods: {}
    }
</script>


<template>
    <div class="description">
        <div
                v-html="description"
                class="description__title"></div>
        <div class="description__disclaimer">
            Disclaimer: this page is dynamically generated by variables in the url, for all the tool settings. Also the title above can be set via the url.
            <b>Be aware that any claim above could be set by anyone</b>.<br><br>
            The data however is all real data. But even so, switching from logarithmic scale to linair scale, or switching
            from absolute to per capita can generate a complete changed perspective. <b>Do not jump to conclusions too fast</b>.
        </div>
    </div>
</template>


<style lang="scss">
    @import '@/styles/variables.scss';

    .description {

        padding: 20px 0;
        margin-left: 70px;

        .description__title {
            font-family: Merriweather;
            font-weight: 400;
            font-size: 24px;
            line-height: 1;
            margin-bottom: 8px;
        }

        .description__disclaimer {
            max-width: 700px;
            font-style: italic;
        }
    }
</style>